[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 12
normal = { family = "JetBrainsMono Nerd Font" }

[general]
import = ["~/.config/alacritty/theme.toml"]

[keyboard]
bindings = [
  { key = "Return", mods = "Shift|Alt", action = "SpawnNewInstance" },
  { key = "Return", mods = "Shift", chars = "\u2b91" },
  { key = "Return", mods = "Control", chars = "\u2b90" },
]

[mouse]
hide_when_typing = true

[scrolling]
history = 8192
multiplier = 4

[window]
dimensions = { columns = 110, lines = 30 }
dynamic_padding = true
opacity = 0.75
